# \uc6b4\uc601\uc11c\ubc84 \ud0c0\uc785(WINDOWS, UNIX)
Globals.DbType=maria
spring.config.activate.on-profile=prod
#hsql - local hssql \uc0ac\uc6a9\uc2dc\uc5d0 \uc801\uc6a9 (\ub0b4\uc7a5 hsql\uc740 \uc815\ubcf4 \ud544\uc694 \uc5c6\uc74c)
#Globals.hsql.DriverClassName=net.sf.log4jdbc.DriverSpy
#Globals.hsql.Url=jdbc:log4jdbc:hsqldb:hsql://127.0.0.1/sampledb
#Globals.hsql.UserName=sa
#Globals.hsql.Password=
#
#logging.rollingpolicy.maxHistory=2

# File store Path
Globals.fileStorePath=/home/upload

# DataSource setting (MariaDB)
Globals.maria.DriverClassName=org.mariadb.jdbc.Driver
Globals.maria.Url=jdbc:mariadb://mariadb-server:3306/schm_bio_mbr?rewriteBatchedStatements=true
Globals.maria.UserName=root
Globals.maria.Password=dev123!@#
#Globals.maria.DriverClassName=org.mariadb.jdbc.Driver
#Globals.maria.Url=jdbc:mariadb://1.233.95.140:13306/kbio?rewriteBatchedStatements=true
#Globals.maria.UserName=root
#Globals.maria.Password=epqmwlttn1q2w3e

#JPA setting
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#multipart Active
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Pageable Default
spring.data.web.pageable.default-page-size=10

# UPLOAD PATH
File.Server.Path =/home/
File.Server.Dir=/home/upload
File.Server.CkeditorDir=/home/ckeditor/

#Logging
logging.root.level=DEBUG
logging.file.name=backend
logging.file.path=./log
logging.rollingpolicy.maxFileSize=10MB
logging.rollingpolicy.maxHistory=30

Globals.crypto.algoritm = egovframe
Globals.jwt.secret=eakbVCaJKsLEBtEI6jiM6E2lqb+nzfpwsTQQY1DoPiA=

Globals.fileUpload.Extensions.Images=.gif.jpg.jpeg.png
Globals.fileUpload.Extensions=.gif.jpg.jpeg.png.xls.xlsx

#Redis Setting
spring.redis.host=redis-server
spring.redis.port=6379
spring.redis.password=epqmwlttn1q2w3e
Globals.redis.dataBase=0,1
#spring.redis.host=1.233.95.140
#spring.redis.port=50055
#spring.redis.password=epqmwlttn1q2w3e
#Globals.redis.dataBase=0,1

Globals.google.clientId=995067628004-3e6phgos7lgh8gvhmhr72c32tbilt960.apps.googleusercontent.com
Globals.google.clientPassword=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
Globals.google.redirectUri=http://localhost:3000/login/google/callback

Globals.naver.clientId=npf9oKYo7QVaALFKsJHM
Globals.naver.tokenUrl=https://nid.naver.com/oauth2.0/token
Globals.naver.infoUrl=https://openapi.naver.com/v1/nid/me

Globals.kakao.clientId=b254f0b8323388912515b2a6c68a274a
Globals.kakao.scriptid=422da0a87d36152b5977374de1f631f7
Globals.kakao.tokenUrl=https://kauth.kakao.com/oauth/token
Globals.kakao.infoUrl=https://kapi.kakao.com/v2/user/me

GLobals.mail.id=gksthe@gmail.com
GLobals.mail.password=mqhgtubmkdtpsoaa