# \uc6b4\uc601\uc11c\ubc84 \ud0c0\uc785(WINDOWS, UNIX)
spring.config.activate.on-profile=dev
#hsql - local hssql \uc0ac\uc6a9\uc2dc\uc5d0 \uc801\uc6a9 (\ub0b4\uc7a5 hsql\uc740 \uc815\ubcf4 \ud544\uc694 \uc5c6\uc74c)
#Globals.hsql.DriverClassName=net.sf.log4jdbc.DriverSpy
#Globals.hsql.Url=jdbc:log4jdbc:hsqldb:hsql://127.0.0.1/sampledb
#Globals.hsql.UserName=sa
#Globals.hsql.Password=
#
#logging.rollingpolicy.maxHistory=2

# File store Path
#Globals.fileStorePath=./files

# DataSource setting (MariaDB)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://1.233.95.140:13306/kbio?rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=epqmwlttn1q2w3e

#JPA setting
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#multipart Active
spring.servlet.multipart.enabled=true

#Pageable Default
spring.data.web.pageable.default-page-size=10

#Setting the maximum file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# UPLOAD PATH
File.Server.Path =/home/
File.Server.Dir=/home/upload
File.Server.CkeditorDir=/home/ckeditor/